//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XPath1Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IXPath1Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMain([NotNull] XPath1Parser.MainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.locationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocationPath([NotNull] XPath1Parser.LocationPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.absoluteLocationPathNoroot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsoluteLocationPathNoroot([NotNull] XPath1Parser.AbsoluteLocationPathNorootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.relativeLocationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelativeLocationPath([NotNull] XPath1Parser.RelativeLocationPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep([NotNull] XPath1Parser.StepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.axisSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxisSpecifier([NotNull] XPath1Parser.AxisSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeTest([NotNull] XPath1Parser.NodeTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] XPath1Parser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.abbreviatedStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbbreviatedStep([NotNull] XPath1Parser.AbbreviatedStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] XPath1Parser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] XPath1Parser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] XPath1Parser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.unionExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionExprNoRoot([NotNull] XPath1Parser.UnionExprNoRootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.pathExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathExprNoRoot([NotNull] XPath1Parser.PathExprNoRootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.filterExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilterExpr([NotNull] XPath1Parser.FilterExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] XPath1Parser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] XPath1Parser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] XPath1Parser.EqualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] XPath1Parser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] XPath1Parser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] XPath1Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.unaryExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExprNoRoot([NotNull] XPath1Parser.UnaryExprNoRootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQName([NotNull] XPath1Parser.QNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] XPath1Parser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableReference([NotNull] XPath1Parser.VariableReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameTest([NotNull] XPath1Parser.NameTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNCName([NotNull] XPath1Parser.NCNameContext context);
}
