//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XPath1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IXPath1Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain([NotNull] XPath1Parser.MainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain([NotNull] XPath1Parser.MainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.locationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocationPath([NotNull] XPath1Parser.LocationPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.locationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocationPath([NotNull] XPath1Parser.LocationPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.absoluteLocationPathNoroot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsoluteLocationPathNoroot([NotNull] XPath1Parser.AbsoluteLocationPathNorootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.absoluteLocationPathNoroot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsoluteLocationPathNoroot([NotNull] XPath1Parser.AbsoluteLocationPathNorootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.relativeLocationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelativeLocationPath([NotNull] XPath1Parser.RelativeLocationPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.relativeLocationPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelativeLocationPath([NotNull] XPath1Parser.RelativeLocationPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStep([NotNull] XPath1Parser.StepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStep([NotNull] XPath1Parser.StepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.axisSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxisSpecifier([NotNull] XPath1Parser.AxisSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.axisSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxisSpecifier([NotNull] XPath1Parser.AxisSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNodeTest([NotNull] XPath1Parser.NodeTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNodeTest([NotNull] XPath1Parser.NodeTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] XPath1Parser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] XPath1Parser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.abbreviatedStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbbreviatedStep([NotNull] XPath1Parser.AbbreviatedStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.abbreviatedStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbbreviatedStep([NotNull] XPath1Parser.AbbreviatedStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] XPath1Parser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] XPath1Parser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] XPath1Parser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] XPath1Parser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] XPath1Parser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] XPath1Parser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.unionExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionExprNoRoot([NotNull] XPath1Parser.UnionExprNoRootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.unionExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionExprNoRoot([NotNull] XPath1Parser.UnionExprNoRootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.pathExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathExprNoRoot([NotNull] XPath1Parser.PathExprNoRootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.pathExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathExprNoRoot([NotNull] XPath1Parser.PathExprNoRootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.filterExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterExpr([NotNull] XPath1Parser.FilterExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.filterExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterExpr([NotNull] XPath1Parser.FilterExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] XPath1Parser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] XPath1Parser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] XPath1Parser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] XPath1Parser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] XPath1Parser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] XPath1Parser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] XPath1Parser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] XPath1Parser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] XPath1Parser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] XPath1Parser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] XPath1Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] XPath1Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.unaryExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExprNoRoot([NotNull] XPath1Parser.UnaryExprNoRootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.unaryExprNoRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExprNoRoot([NotNull] XPath1Parser.UnaryExprNoRootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQName([NotNull] XPath1Parser.QNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQName([NotNull] XPath1Parser.QNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionName([NotNull] XPath1Parser.FunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionName([NotNull] XPath1Parser.FunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableReference([NotNull] XPath1Parser.VariableReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableReference([NotNull] XPath1Parser.VariableReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameTest([NotNull] XPath1Parser.NameTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameTest([NotNull] XPath1Parser.NameTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNCName([NotNull] XPath1Parser.NCNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNCName([NotNull] XPath1Parser.NCNameContext context);
}
