//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXPath1Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class XPath1BaseListener : IXPath1Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] XPath1Parser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] XPath1Parser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.locationPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationPath([NotNull] XPath1Parser.LocationPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.locationPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationPath([NotNull] XPath1Parser.LocationPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.absoluteLocationPathNoroot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsoluteLocationPathNoroot([NotNull] XPath1Parser.AbsoluteLocationPathNorootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.absoluteLocationPathNoroot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsoluteLocationPathNoroot([NotNull] XPath1Parser.AbsoluteLocationPathNorootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.relativeLocationPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelativeLocationPath([NotNull] XPath1Parser.RelativeLocationPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.relativeLocationPath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelativeLocationPath([NotNull] XPath1Parser.RelativeLocationPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStep([NotNull] XPath1Parser.StepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.step"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStep([NotNull] XPath1Parser.StepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.axisSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxisSpecifier([NotNull] XPath1Parser.AxisSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.axisSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxisSpecifier([NotNull] XPath1Parser.AxisSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nodeTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodeTest([NotNull] XPath1Parser.NodeTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nodeTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodeTest([NotNull] XPath1Parser.NodeTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] XPath1Parser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] XPath1Parser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.abbreviatedStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbbreviatedStep([NotNull] XPath1Parser.AbbreviatedStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.abbreviatedStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbbreviatedStep([NotNull] XPath1Parser.AbbreviatedStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] XPath1Parser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] XPath1Parser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] XPath1Parser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] XPath1Parser.PrimaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] XPath1Parser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] XPath1Parser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.unionExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionExprNoRoot([NotNull] XPath1Parser.UnionExprNoRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.unionExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionExprNoRoot([NotNull] XPath1Parser.UnionExprNoRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.pathExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathExprNoRoot([NotNull] XPath1Parser.PathExprNoRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.pathExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathExprNoRoot([NotNull] XPath1Parser.PathExprNoRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.filterExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterExpr([NotNull] XPath1Parser.FilterExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.filterExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterExpr([NotNull] XPath1Parser.FilterExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] XPath1Parser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] XPath1Parser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] XPath1Parser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] XPath1Parser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] XPath1Parser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] XPath1Parser.EqualityExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] XPath1Parser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] XPath1Parser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpr([NotNull] XPath1Parser.AdditiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpr([NotNull] XPath1Parser.AdditiveExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpr([NotNull] XPath1Parser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpr([NotNull] XPath1Parser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.unaryExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExprNoRoot([NotNull] XPath1Parser.UnaryExprNoRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.unaryExprNoRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExprNoRoot([NotNull] XPath1Parser.UnaryExprNoRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.qName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQName([NotNull] XPath1Parser.QNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.qName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQName([NotNull] XPath1Parser.QNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionName([NotNull] XPath1Parser.FunctionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionName([NotNull] XPath1Parser.FunctionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableReference([NotNull] XPath1Parser.VariableReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableReference([NotNull] XPath1Parser.VariableReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nameTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameTest([NotNull] XPath1Parser.NameTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nameTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameTest([NotNull] XPath1Parser.NameTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1Parser.nCName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNCName([NotNull] XPath1Parser.NCNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1Parser.nCName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNCName([NotNull] XPath1Parser.NCNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
