//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1W3.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXPath1W3Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class XPath1W3BaseListener : IXPath1W3Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] XPath1W3Parser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] XPath1W3Parser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.exprSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprSingle([NotNull] XPath1W3Parser.ExprSingleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.exprSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprSingle([NotNull] XPath1W3Parser.ExprSingleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.operatorExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorExpr([NotNull] XPath1W3Parser.OperatorExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.operatorExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorExpr([NotNull] XPath1W3Parser.OperatorExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] XPath1W3Parser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] XPath1W3Parser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] XPath1W3Parser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] XPath1W3Parser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] XPath1W3Parser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] XPath1W3Parser.EqualityExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] XPath1W3Parser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] XPath1W3Parser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpr([NotNull] XPath1W3Parser.AdditiveExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.additiveExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpr([NotNull] XPath1W3Parser.AdditiveExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpr([NotNull] XPath1W3Parser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.multiplicativeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpr([NotNull] XPath1W3Parser.MultiplicativeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] XPath1W3Parser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] XPath1W3Parser.UnaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.unionExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionExpr([NotNull] XPath1W3Parser.UnionExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.unionExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionExpr([NotNull] XPath1W3Parser.UnionExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.valueExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExpr([NotNull] XPath1W3Parser.ValueExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.valueExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExpr([NotNull] XPath1W3Parser.ValueExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.pathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathExpr([NotNull] XPath1W3Parser.PathExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.pathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathExpr([NotNull] XPath1W3Parser.PathExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.relativePathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelativePathExpr([NotNull] XPath1W3Parser.RelativePathExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.relativePathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelativePathExpr([NotNull] XPath1W3Parser.RelativePathExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.stepExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStepExpr([NotNull] XPath1W3Parser.StepExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.stepExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStepExpr([NotNull] XPath1W3Parser.StepExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.axisStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxisStep([NotNull] XPath1W3Parser.AxisStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.axisStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxisStep([NotNull] XPath1W3Parser.AxisStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.forwardStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForwardStep([NotNull] XPath1W3Parser.ForwardStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.forwardStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForwardStep([NotNull] XPath1W3Parser.ForwardStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.forwardAxis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForwardAxis([NotNull] XPath1W3Parser.ForwardAxisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.forwardAxis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForwardAxis([NotNull] XPath1W3Parser.ForwardAxisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.abbrevForwardStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbbrevForwardStep([NotNull] XPath1W3Parser.AbbrevForwardStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.abbrevForwardStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbbrevForwardStep([NotNull] XPath1W3Parser.AbbrevForwardStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.reverseStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReverseStep([NotNull] XPath1W3Parser.ReverseStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.reverseStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReverseStep([NotNull] XPath1W3Parser.ReverseStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.reverseAxis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReverseAxis([NotNull] XPath1W3Parser.ReverseAxisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.reverseAxis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReverseAxis([NotNull] XPath1W3Parser.ReverseAxisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.abbrevReverseStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbbrevReverseStep([NotNull] XPath1W3Parser.AbbrevReverseStepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.abbrevReverseStep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbbrevReverseStep([NotNull] XPath1W3Parser.AbbrevReverseStepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nodeTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodeTest([NotNull] XPath1W3Parser.NodeTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nodeTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodeTest([NotNull] XPath1W3Parser.NodeTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nameTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameTest([NotNull] XPath1W3Parser.NameTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nameTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameTest([NotNull] XPath1W3Parser.NameTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.wildCard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWildCard([NotNull] XPath1W3Parser.WildCardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.wildCard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWildCard([NotNull] XPath1W3Parser.WildCardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] XPath1W3Parser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] XPath1W3Parser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] XPath1W3Parser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.primaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] XPath1W3Parser.PrimaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarRef([NotNull] XPath1W3Parser.VarRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarRef([NotNull] XPath1W3Parser.VarRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarName([NotNull] XPath1W3Parser.VarNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarName([NotNull] XPath1W3Parser.VarNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.parenthesizedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedExpr([NotNull] XPath1W3Parser.ParenthesizedExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.parenthesizedExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedExpr([NotNull] XPath1W3Parser.ParenthesizedExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.contextItemExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContextItemExpr([NotNull] XPath1W3Parser.ContextItemExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.contextItemExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContextItemExpr([NotNull] XPath1W3Parser.ContextItemExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] XPath1W3Parser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] XPath1W3Parser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.kindTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKindTest([NotNull] XPath1W3Parser.KindTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.kindTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKindTest([NotNull] XPath1W3Parser.KindTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.anyKindTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnyKindTest([NotNull] XPath1W3Parser.AnyKindTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.anyKindTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnyKindTest([NotNull] XPath1W3Parser.AnyKindTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.textTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextTest([NotNull] XPath1W3Parser.TextTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.textTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextTest([NotNull] XPath1W3Parser.TextTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.commentTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentTest([NotNull] XPath1W3Parser.CommentTestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.commentTest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentTest([NotNull] XPath1W3Parser.CommentTestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nCName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNCName([NotNull] XPath1W3Parser.NCNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nCName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNCName([NotNull] XPath1W3Parser.NCNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.qName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQName([NotNull] XPath1W3Parser.QNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.qName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQName([NotNull] XPath1W3Parser.QNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.functionQName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionQName([NotNull] XPath1W3Parser.FunctionQNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.functionQName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionQName([NotNull] XPath1W3Parser.FunctionQNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
