//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1W3.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XPath1W3Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IXPath1W3Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] XPath1W3Parser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] XPath1W3Parser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.exprSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprSingle([NotNull] XPath1W3Parser.ExprSingleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.exprSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprSingle([NotNull] XPath1W3Parser.ExprSingleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.operatorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorExpr([NotNull] XPath1W3Parser.OperatorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.operatorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorExpr([NotNull] XPath1W3Parser.OperatorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] XPath1W3Parser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] XPath1W3Parser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] XPath1W3Parser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] XPath1W3Parser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] XPath1W3Parser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] XPath1W3Parser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] XPath1W3Parser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] XPath1W3Parser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] XPath1W3Parser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] XPath1W3Parser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] XPath1W3Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] XPath1W3Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] XPath1W3Parser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] XPath1W3Parser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.unionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionExpr([NotNull] XPath1W3Parser.UnionExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.unionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionExpr([NotNull] XPath1W3Parser.UnionExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueExpr([NotNull] XPath1W3Parser.ValueExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueExpr([NotNull] XPath1W3Parser.ValueExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.pathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathExpr([NotNull] XPath1W3Parser.PathExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.pathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathExpr([NotNull] XPath1W3Parser.PathExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.relativePathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelativePathExpr([NotNull] XPath1W3Parser.RelativePathExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.relativePathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelativePathExpr([NotNull] XPath1W3Parser.RelativePathExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.stepExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStepExpr([NotNull] XPath1W3Parser.StepExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.stepExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStepExpr([NotNull] XPath1W3Parser.StepExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.axisStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxisStep([NotNull] XPath1W3Parser.AxisStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.axisStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxisStep([NotNull] XPath1W3Parser.AxisStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.forwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForwardStep([NotNull] XPath1W3Parser.ForwardStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.forwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForwardStep([NotNull] XPath1W3Parser.ForwardStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.forwardAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForwardAxis([NotNull] XPath1W3Parser.ForwardAxisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.forwardAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForwardAxis([NotNull] XPath1W3Parser.ForwardAxisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.abbrevForwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbbrevForwardStep([NotNull] XPath1W3Parser.AbbrevForwardStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.abbrevForwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbbrevForwardStep([NotNull] XPath1W3Parser.AbbrevForwardStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.reverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReverseStep([NotNull] XPath1W3Parser.ReverseStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.reverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReverseStep([NotNull] XPath1W3Parser.ReverseStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.reverseAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReverseAxis([NotNull] XPath1W3Parser.ReverseAxisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.reverseAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReverseAxis([NotNull] XPath1W3Parser.ReverseAxisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.abbrevReverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbbrevReverseStep([NotNull] XPath1W3Parser.AbbrevReverseStepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.abbrevReverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbbrevReverseStep([NotNull] XPath1W3Parser.AbbrevReverseStepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNodeTest([NotNull] XPath1W3Parser.NodeTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNodeTest([NotNull] XPath1W3Parser.NodeTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameTest([NotNull] XPath1W3Parser.NameTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameTest([NotNull] XPath1W3Parser.NameTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.wildCard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWildCard([NotNull] XPath1W3Parser.WildCardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.wildCard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWildCard([NotNull] XPath1W3Parser.WildCardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] XPath1W3Parser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] XPath1W3Parser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] XPath1W3Parser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] XPath1W3Parser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRef([NotNull] XPath1W3Parser.VarRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRef([NotNull] XPath1W3Parser.VarRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] XPath1W3Parser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] XPath1W3Parser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.parenthesizedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpr([NotNull] XPath1W3Parser.ParenthesizedExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.parenthesizedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpr([NotNull] XPath1W3Parser.ParenthesizedExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.contextItemExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContextItemExpr([NotNull] XPath1W3Parser.ContextItemExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.contextItemExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContextItemExpr([NotNull] XPath1W3Parser.ContextItemExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] XPath1W3Parser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] XPath1W3Parser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.kindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKindTest([NotNull] XPath1W3Parser.KindTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.kindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKindTest([NotNull] XPath1W3Parser.KindTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.anyKindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnyKindTest([NotNull] XPath1W3Parser.AnyKindTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.anyKindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnyKindTest([NotNull] XPath1W3Parser.AnyKindTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.textTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextTest([NotNull] XPath1W3Parser.TextTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.textTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextTest([NotNull] XPath1W3Parser.TextTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.commentTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentTest([NotNull] XPath1W3Parser.CommentTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.commentTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentTest([NotNull] XPath1W3Parser.CommentTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNCName([NotNull] XPath1W3Parser.NCNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNCName([NotNull] XPath1W3Parser.NCNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQName([NotNull] XPath1W3Parser.QNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQName([NotNull] XPath1W3Parser.QNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XPath1W3Parser.functionQName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionQName([NotNull] XPath1W3Parser.FunctionQNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XPath1W3Parser.functionQName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionQName([NotNull] XPath1W3Parser.FunctionQNameContext context);
}
