//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XPath1W3.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XPath1W3Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IXPath1W3Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] XPath1W3Parser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.exprSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprSingle([NotNull] XPath1W3Parser.ExprSingleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.operatorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorExpr([NotNull] XPath1W3Parser.OperatorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] XPath1W3Parser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] XPath1W3Parser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpr([NotNull] XPath1W3Parser.EqualityExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] XPath1W3Parser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.additiveExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpr([NotNull] XPath1W3Parser.AdditiveExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.multiplicativeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpr([NotNull] XPath1W3Parser.MultiplicativeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] XPath1W3Parser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.unionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionExpr([NotNull] XPath1W3Parser.UnionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpr([NotNull] XPath1W3Parser.ValueExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.pathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathExpr([NotNull] XPath1W3Parser.PathExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.relativePathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelativePathExpr([NotNull] XPath1W3Parser.RelativePathExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.stepExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStepExpr([NotNull] XPath1W3Parser.StepExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.axisStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxisStep([NotNull] XPath1W3Parser.AxisStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.forwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForwardStep([NotNull] XPath1W3Parser.ForwardStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.forwardAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForwardAxis([NotNull] XPath1W3Parser.ForwardAxisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.abbrevForwardStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbbrevForwardStep([NotNull] XPath1W3Parser.AbbrevForwardStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.reverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReverseStep([NotNull] XPath1W3Parser.ReverseStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.reverseAxis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReverseAxis([NotNull] XPath1W3Parser.ReverseAxisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.abbrevReverseStep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbbrevReverseStep([NotNull] XPath1W3Parser.AbbrevReverseStepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.nodeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeTest([NotNull] XPath1W3Parser.NodeTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.nameTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameTest([NotNull] XPath1W3Parser.NameTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.wildCard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildCard([NotNull] XPath1W3Parser.WildCardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] XPath1W3Parser.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] XPath1W3Parser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarRef([NotNull] XPath1W3Parser.VarRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarName([NotNull] XPath1W3Parser.VarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.parenthesizedExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedExpr([NotNull] XPath1W3Parser.ParenthesizedExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.contextItemExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextItemExpr([NotNull] XPath1W3Parser.ContextItemExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] XPath1W3Parser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.kindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKindTest([NotNull] XPath1W3Parser.KindTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.anyKindTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyKindTest([NotNull] XPath1W3Parser.AnyKindTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.textTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextTest([NotNull] XPath1W3Parser.TextTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.commentTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommentTest([NotNull] XPath1W3Parser.CommentTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.nCName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNCName([NotNull] XPath1W3Parser.NCNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.qName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQName([NotNull] XPath1W3Parser.QNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XPath1W3Parser.functionQName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionQName([NotNull] XPath1W3Parser.FunctionQNameContext context);
}
